/**
 * Citations — the link between a figure in `src/domain` and the gazette line it came from.
 *
 * Chapter 16 taught the lesson this file exists to institutionalise. Six errors survived
 * in the compounding engine for as long as they did because nothing connected a constant
 * to a sentence. A comment saying "Chapter 16.3" is not a citation: it cannot be checked,
 * it does not notice when the source is re-extracted, and it does not distinguish a rule
 * someone read from a rule someone assumed.
 *
 * Two kinds, because the gazette states rules two ways.
 *
 *   `prose` — a sentence, checked as a verbatim line of the source.
 *   `cells` — a table, checked as the exact sequence of non-empty cell values across a
 *             span of lines. Numeric tables flatten to one value per line, so a sentence
 *             quote cannot capture them; the cell sequence is a fingerprint of the whole
 *             table and drifts the moment any figure in it changes.
 *
 * `src/domain/rules/__tests__/citations.test.ts` checks every entry against
 * `docs/source/gazette-tmpr8.txt` on every run, and refuses to let a rule be marked
 * `confidence: 'gazette'` without one. Generated from the source by line number rather
 * than typed, so the quotes cannot be mistyped into agreement with the code.
 */

/** Path is relative to the repository root. */
export const GAZETTE_SOURCE = 'docs/source/gazette-tmpr8.txt';

interface CitationBase {
  /** Unique id for this citation. */
  readonly id: string;
  /** The rule in `registry.ts` this supports. */
  readonly rule: string;
  /** Clause reference as the gazette numbers it. */
  readonly clause: string;
  /** What in `src/domain` rests on this, and what is still missing from it. */
  readonly supports: string;
  /**
   * The gazette's own printed page, where a chapter PDF has established it. The flattened
   * text carries no pagination at all, so this is the only number a reader can look up in
   * a printed copy. Informational — the line number is what the test checks.
   */
  readonly gazettePage?: number;
}

export interface ProseCitation extends CitationBase {
  readonly kind: 'prose';
  /** 1-based line in the source file. */
  readonly line: number;
  /** The line, verbatim. Whitespace is normalised when checked. */
  readonly text: string;
}

export interface CellsCitation extends CitationBase {
  readonly kind: 'cells';
  /** Inclusive 1-based line span the table occupies. */
  readonly lines: readonly [number, number];
  /** Every non-empty cell in that span, in order. */
  readonly cells: readonly string[];
}

export type Citation = ProseCitation | CellsCitation;

export const CITATIONS: readonly Citation[] = [
  {
    id: 'setback.plotted-residential.scope',
    rule: 'setback.plotted-residential',
    clause: 'Para 3.2.4.1',
    supports: 'Plot-size bands, and the 15 m / 17.5 m height ceiling that follows the plot rather than the occupancy.',
    kind: 'prose',
    line: 4429,
    text: 'Under plotted development, for all single/multi-units less than 300 square meters plot size, three floors with stilts up to 15 meter is allowed and on plots above 300 square meters, four storeys with stilts up to 17.5-meter height is allowed. The set-back shall be as follows:',
  },
  {
    id: 'setback.plotted-residential.table',
    rule: 'setback.plotted-residential',
    clause: 'Para 3.2.4.1 Table',
    supports: 'PLOTTED_RESIDENTIAL_LADDER — front, rear, side-1, side-2 by plot area.',
    kind: 'cells',
    lines: [4446, 4487],
    cells: [
      'Up to 150',
      '1',
      '0',
      '0',
      '0',
      '>150 to 300',
      '3',
      '1.5',
      '0',
      '0',
      '>300 to 500',
      '3',
      '3',
      '0',
      '0',
      '(b) Semi-detached',
      '>500 to 1200',
      '4.5',
      '4.5',
      '1.5',
      '0',
      '(c) Detached',
      '>1200',
      '6',
      '6',
      '1.5',
      '1.5',
    ],
  },
  {
    id: 'setback.plotted-residential.note1',
    rule: 'setback.plotted-residential',
    clause: 'Para 3.2.4.1 Note-1',
    supports: 'The 40% rear-setback allowance the compounding table at 16.2 refers to. Not yet modelled.',
    kind: 'prose',
    line: 4489,
    text: 'Note-1: Construction shall be permitted on 40 percent of the rear setback up to 7 meter height, in semi-detached buildings. But in corner plots the said covering shall be permissible only after leaving the side set back. In case of stilt floor, construction on 40 percent area of the rear setback shall not be allowed.',
  },
  {
    id: 'setback.plotted-residential.note2',
    rule: 'setback.plotted-residential',
    clause: 'Para 3.2.4.1 Note-2',
    supports: 'Corner plots: new layouts take the front setback on the side; approved layouts take 1.5 m up to 500 sqm.',
    kind: 'prose',
    line: 4490,
    text: 'Note-2: The side setback in a corner plot in the new layouts shall be the same as the front setback of the concerned plot. In already approved layouts, if setback is not prescribed in the layout plan, the minimum side set-back in corner plots up to 500 square meters shall be 1.5 meters and in corner plots having area more than 500 square meters, the side set-back shall be as per the above table.',
  },
  {
    id: 'setback.high-rise.scope',
    rule: 'setback.high-rise',
    clause: 'Para 3.2.4.9',
    supports: 'The scope qualifier: this table governs occupancies OTHER THAN single/multi units.',
    kind: 'prose',
    line: 4802,
    text: 'For use occupancies with building height more than 15m (other than single/multi units), the minimum setback requirement shall be as follows.',
  },
  {
    id: 'setback.high-rise.table',
    rule: 'setback.high-rise',
    clause: 'Para 3.2.4.9 Table',
    supports: 'HIGH_RISE_LADDER — eight height bands from >15 m to >51 m.',
    kind: 'cells',
    lines: [4803, 4857],
    cells: [
      'Building Height (in meters)',
      'Front (m)',
      'Rear (m)',
      'Side-1 (m)',
      'Side-2 (m)',
      '>15 – 17.5',
      '5',
      '5',
      '5',
      '5',
      '>17.5 - 21',
      '6',
      '6',
      '6',
      '6',
      '>21 - 27',
      '7',
      '7',
      '7',
      '7',
      '>27 - 33',
      '8',
      '8',
      '8',
      '8',
      '>33 - 39',
      '9',
      '9',
      '9',
      '9',
      '>39 - 45',
      '10',
      '10',
      '10',
      '10',
      '>45 - 51',
      '11',
      '11',
      '11',
      '11',
      '>51',
      '15',
      '12',
      '12',
      '12',
    ],
  },
  {
    id: 'setback.high-rise.note1',
    rule: 'setback.high-rise',
    clause: 'Para 3.2.4.9 Note-1',
    supports: 'On a plot facing two roads, the side towards the wider road is the front. Not yet modelled.',
    kind: 'prose',
    line: 4859,
    text: 'Note-1: For buildings situated on two or more roads of different road widths, then the side of the building towards the wider road shall be considered as the front.',
  },
  {
    id: 'setback.high-rise.note2',
    rule: 'setback.high-rise',
    clause: 'Para 3.2.4.9 Note-2',
    supports: 'An alternative setback path exists. Not yet modelled.',
    kind: 'prose',
    line: 4860,
    text: 'Note-2: In alternative to the above-mentioned table of paragraph 3.2.4.9, following setbacks shall be allowed.',
  },
  {
    id: 'far.telescopic-residential.method',
    rule: 'far.telescopic-residential',
    clause: 'Para 3.2.5',
    supports: 'Floor area is computed telescopically, band by band, not on a single rate for the whole plot.',
    kind: 'prose',
    line: 2296,
    text: 'The calculation of floor area shall be conducted telescopically, beginning from one level below the area of the proposed plot.',
  },
  {
    id: 'far.telescopic-residential.table',
    rule: 'far.telescopic-residential',
    clause: 'Para 3.2.5 Table',
    supports: 'RESIDENTIAL_TELESCOPIC_SLABS and PLOTTED_RESIDENTIAL_MAX_FAR — base FAR per band, Max FAR 2.0 throughout.',
    kind: 'cells',
    lines: [2318, 2353],
    cells: [
      'Plotted Development – Single Unit/Multi-Unit (Built-up/Non-Built-up)',
      'Max. coverage after ensuring setbacks',
      'Up to 150',
      '2.0',
      '2.0',
      '>150 to 300',
      '1.8',
      '2.0',
      '>300 to 500',
      '1.75',
      '2.0',
      '>500 to 1200',
      '1.5',
      '2.0',
      '>1200',
      '1.25',
      '2.0',
    ],
  },
  {
    id: 'compounding.non-compoundable',
    rule: 'compounding.schedule',
    clause: 'Clause 16.1.3',
    supports: 'NonCompoundableFlags — the thirteen offences, in the gazette’s order.',
    kind: 'cells',
    lines: [11094, 11108],
    cells: [
      'Following offences shall not be compoundable.',
      'Construction done on the land reserved for or related to public and semi-public amenities, services and utilities such as road, railway line, park, green verge/belt etc.',
      'Construction done in contravention of land-use prescribed in Master Plan or Zonal Development Plan or Lay-out plan or lease.',
      'Construction done on plots in illegal colonies.',
      'Construction done on government or public land without permission of the concerned department.',
      'Construction done on disputed land.',
      'Construction in the buildings where earthquake resistance measures are mandatory as per chapter 11.8.',
      'Construction of buildings where firefighting requirements are mandatory or where No Objection Certificate (NOC) for construction/addition/alteration has not been obtained from fire authority (wherever mandatory), as per chapter 10.1.3.',
      'Construction in violation of building height in heritage zones, protected monuments, and civil aviation areas or in restricted height areas.',
      'Construction carried out where required parking arrangement is not feasible.',
      'Construction carried out on areas reserved for ‘common areas and facilities’ in group housing and other multi-storey buildings.',
      'Construction done on land covered by ponds/reservoirs, river, drain, etc, identified in Master Plan/Zonal Plan/ Lay-out Plan or recorded in the revenue records.',
      'Construction in the buildings where measures for access to differently abled persons are mandatory as per chapter 12.',
      'Construction undertaken in mixed use development, which violates the criteria of pre-dominant land use.',
    ],
  },
  {
    id: 'compounding.limits',
    rule: 'compounding.schedule',
    clause: 'Clause 16.2 Table',
    supports: 'compoundableLimits() — both columns, every parameter. The column-B setback cell is printed once and spans the front, rear and side rows.',
    kind: 'cells',
    lines: [11113, 11165],
    cells: [
      'Parameter',
      'All Buildings <=15-meter and multi-units upto 17.5 meter height except Group Housing',
      'Buildings >15-meter height and Group Housing except multi-units.',
      'Front Setback',
      '25% of front setback area up to a maximum of',
      '1.0 meter',
      '10 percent of setback area (maximum up to a width of 1-meter), subject to Fire NOC.',
      'Rear Setback',
      'Residential:',
      '(a) Plot Size up to 500 sqm- 100% compoundable in cases where proper provisions have been made for light and ventilation.',
      '(b) Plot Size > 500 sqm - construction up to maximum 10% of the area in rear setback (in addition to permissible 40%)',
      'Others:',
      '10 percent of rear setback area',
      'Side Setback',
      'Construction up to a maximum of 25% of width of side setback',
      'Ground Coverage & FAR',
      'Construction up to a maximum of 10% of total permissible FAR, in addition to permissible ground coverage.',
      'Construction up to a maximum of 10% of total permissible FAR, in addition to permissible ground coverage.',
      'Note: Construction in front, rear and side setbacks shall be counted while calculating the maximum permissible compoundable area.',
      'Note: Construction in front, rear and side setbacks shall be counted while calculating the maximum permissible compoundable area.',
      'Building Height',
      'Construction up to a maximum of 10% height from permissible limit without changing the number of floors',
      '-',
      'Maximum compoundable units',
      'Maximum one unit in plotted development beyond permissible limit',
      'In Group Housing: Proportionate units relative to percentage of compoundable additional FAR/Purchasable FAR',
      'Others',
      'Up to 10 percent of any dimension and area of the items indicated in 16.3.8',
      'Up to 10 percent of any dimension and area of the items indicated in 16.3.8',
    ],
  },
  {
    id: 'compounding.item1',
    rule: 'compounding.schedule',
    clause: 'Clause 16.3.8 Item 1 A',
    supports: 'ITEM1_UNAUTHORISED_WITHIN_ENVELOPE — the first of four plot-size bands.',
    kind: 'prose',
    line: 11202,
    text: '| Rs. 25 per sqm for construction of all nature on plots up to 150 sq meter.',
  },
  {
    id: 'compounding.item1f',
    rule: 'compounding.schedule',
    clause: 'Clause 16.3.8 Item 1 F',
    supports: 'ITEM1F_RATE_PER_EXTRA_UNIT.',
    kind: 'prose',
    line: 11233,
    text: '| On Compoundable units in addition to permissible units- Rs. 122640 per unit.',
  },
  {
    id: 'compounding.item3',
    rule: 'compounding.schedule',
    clause: 'Clause 16.3.8 Item 3',
    supports: 'ITEM3_BEYOND_FAR — the head that charges a per-m² rate AND a share of the land price.',
    kind: 'prose',
    line: 11304,
    text: '| In construction of plotted development and Group Housing-Rs. 491 per sqm. and 50% of required land price for additional floor area.',
  },
  {
    id: 'compounding.item9',
    rule: 'compounding.schedule',
    clause: 'Clause 16.3.8 Item 9',
    supports: 'ITEM9_COMPOUND_WALL — note the minimum, which binds below ~41 running metres.',
    kind: 'prose',
    line: 11419,
    text: '| Rs. 123 per running meter but a minimum of Rs. 5000/-',
  },
  {
    id: 'compounding.item10',
    rule: 'compounding.schedule',
    clause: 'Clause 16.3.8 Item 10',
    supports: 'ITEM10_EXCESS_HEIGHT_RESIDENTIAL_RATE. The quantity this rate multiplies is ambiguous — see V-004b.',
    kind: 'prose',
    line: 11440,
    text: '| @Rs. 6132/- per running meter of height (measured as per',
  },
  {
    id: 'compounding.item12',
    rule: 'compounding.schedule',
    clause: 'Clause 16.3.8 Item 12',
    supports: 'ITEM12_AMENITY_SHORTFALL_MULTIPLE.',
    kind: 'prose',
    line: 11475,
    text: '| Compounding fee at the rate of two times of price of land equivalent to decrease in the area required, as per byelaws, for roads, parks and open spaces and other community amenities.',
  },
  {
    id: 'compounding.note1',
    rule: 'compounding.schedule',
    clause: 'Clause 16.3.8 Note-1',
    supports: 'NOTE1_OTHER_CONTRAVENTION_RATE and USE_MULTIPLIER.',
    kind: 'prose',
    line: 11491,
    text: 'For any construction in contravention of the byelaws (other than those listed in the above schedule) such as – porch, balcony/chhajja etc., but are compoundable; a compounding fee @Rs. 491/- per square meter shall be charged. The rate of compounding fee for commercial shall be two times, for office 1.5 times, for industrial 0.40 times, for facilities and other usages 0.50 times.',
  },
  {
    id: 'compounding.land-rate',
    rule: 'compounding.schedule',
    clause: 'Clause 16.3.6.1',
    supports: 'The land rate is the residential rate whatever the building’s use. The multipliers carry the use, not the rate.',
    kind: 'prose',
    line: 11181,
    text: 'The cost of land shall be assessed at the prevailing residential rate of the Authority, or the non-agriculture circle rate fixed by the District Collector, whichever is higher. For calculation of Compounding fee for all kinds of constructions only the residential rate of the land shall be taken into consideration.',
  },
  {
    id: 'compounding.purchasable-far',
    rule: 'compounding.schedule',
    clause: 'Clause 16.3.7.2',
    supports: 'Purchasable FAR charges are payable on top, except on the first 10%.',
    kind: 'prose',
    line: 11183,
    text: 'In addition to charges payable as per rules for purchasable FAR, Compounding fee shall also be payable at the rates prescribed under Serial No.-2 of the Schedule. However, purchasable FAR charges for first 10% purchasable FAR shall not be payable.',
  },
  {
    id: 'far.group-housing.built-up',
    rule: 'far.road-width-group-housing',
    clause: 'Para 3.2.5 Table row 2(a)',
    supports: 'GROUP_HOUSING_MAX_FAR.built_up and BASE_FAR.group_housing.built_up.',
    kind: 'cells',
    lines: [2364, 2403],
    cells: [
      '2(a)',
      'Group Housing',
      '(Built up)',
      'Max. coverage after ensuring setbacks',
      '9 – 12m',
      '1.5',
      '2.0',
      '>12 – 18m',
      '1.5',
      '3.0',
      '>18 – 24m',
      '1.5',
      '3.0',
      '>24 – 45m',
      '1.5',
      '5.25',
      '> 45m',
      '1.5',
      'Unrestricted',
    ],
  },
  {
    id: 'far.group-housing.non-built-up',
    rule: 'far.road-width-group-housing',
    clause: 'Para 3.2.5 Table row 2(b)',
    supports: 'GROUP_HOUSING_MAX_FAR.non_built_up. Note the first band is >12 m: the gazette prints no 9-12 m row for a new layout.',
    kind: 'cells',
    lines: [2405, 2435],
    cells: [
      '2(b)',
      'Group Housing',
      '(Non-Built up)',
      'Max. coverage after ensuring setbacks',
      '>12 – 18m',
      '2.5',
      '5.0',
      '>18 – 24m',
      '2.5',
      '5.0',
      '>24 – 45m',
      '2.5',
      '8.75',
      '> 45m',
      '2.5',
      'Unrestricted',
    ],
  },
  {
    id: 'social.ews-lig.reservation',
    rule: 'social.ews-lig',
    clause: 'Clause 4.3.1',
    supports: 'assessSocialHousing() — the trigger is "more than one unit", the exemption is an affordable housing scheme, and the shelter fee exists only below 4 Ha.',
    gazettePage: 79,
    kind: 'prose',
    line: 5890,
    text: 'For all housing projects (except affordable housing schemes) having more than one unit, a 10% each of the total units shall be mandatorily reserved for Economically Weaker Section (EWS) and Lower Income Group (LIG) housing respectively. For plots less than 4 Ha, provision to deposit shelter fee shall be applicable.',
  },
  {
    id: 'social.ews-lig.fee-formula',
    rule: 'social.ews-lig',
    clause: 'Clause 4.3.11',
    supports: 'SHELTER_FEE_SQM_PER_UNIT. The unit count factors out, giving 6.5 × circle rate per dwelling unit.',
    gazettePage: 81,
    kind: 'prose',
    line: 5953,
    text: '10% of [(total number of dwelling units) X (minimum EWS dwelling unit carpet area + minimum LIG dwelling unit carpet area) X Circle Rate]',
  },
  {
    id: 'social.ews-lig.affordable-exemption',
    rule: 'social.ews-lig',
    clause: 'Clause 4.4 Note-2',
    supports: 'The affordable-housing exemption, which the engine did not model at all.',
    gazettePage: 81,
    kind: 'prose',
    line: 5976,
    text: 'Note-2: In such affordable housing schemes, the provisions of paragraph 4.3.1 shall not be applicable,',
  },
  {
    id: 'occupancy.res-single.plot',
    rule: 'occupancy.thresholds',
    clause: 'Clause 4.1.2(i)',
    supports: 'res_single.minPlotAreaSqm — 40 m² in a new layout, unrestricted in a built-up area.',
    gazettePage: 76,
    kind: 'prose',
    line: 5660,
    text: 'The minimum plot size for single units shall be 40 square meters for non-built-up area and there shall be no restriction on plot size for built-up area.',
  },
  {
    id: 'occupancy.res-multi.plot',
    rule: 'occupancy.thresholds',
    clause: 'Clause 4.1.2(ii)',
    supports: 'res_multi.minPlotAreaSqm. Each unit must also have ≥60 m² carpet, which is not yet modelled.',
    gazettePage: 76,
    kind: 'prose',
    line: 5661,
    text: 'The minimum plot size for multi units shall be 150 square meters.',
  },
  {
    id: 'occupancy.res.height',
    rule: 'occupancy.thresholds',
    clause: 'Clause 4.1.4',
    supports: 'res_single.maxHeightM 15 m and res_multi 17.5 m. Conflicts with Clause 3.2.4.1, which keys the same ceiling on plot size — see V-010.',
    gazettePage: 76,
    kind: 'prose',
    line: 5667,
    text: 'The maximum height of the building shall be 15-m including stilt for single unit and 17.5 meters including mandatory stilt floor for multi-unit.',
  },
  {
    id: 'occupancy.group-housing.plot',
    rule: 'occupancy.thresholds',
    clause: 'Clause 4.2.2',
    supports: 'res_group_housing.minPlotAreaSqm — 1000 m² built-up, 1500 m² in a new layout.',
    gazettePage: 77,
    kind: 'prose',
    line: 5717,
    text: 'The minimum area of the plot for group housing schemes in built-up area shall be 1000 square meters and 1500 square meters in non-built-up areas.',
  },
  {
    id: 'occupancy.group-housing.road',
    rule: 'occupancy.thresholds',
    clause: 'Clause 4.2.3',
    supports: 'res_group_housing.minRoadWidthM — 9 m built-up, 12 m in a new layout.',
    gazettePage: 77,
    kind: 'prose',
    line: 5719,
    text: 'The proposed plot for group housing shall be located on road of minimum 12-meter width in non-built-up areas and the minimum road width for group housing plots in built-up area shall be 9-meters. The specifications for internal roads and pathways shall be as per paragraph 3.1.3 of these byelaws.',
  },
  {
    id: 'occupancy.group-housing.height',
    rule: 'occupancy.thresholds',
    clause: 'Clause 4.2.4',
    supports: 'res_group_housing.maxHeightM = Infinity, governed instead by monument, airport funnel and other statutory limits.',
    gazettePage: 77,
    kind: 'prose',
    line: 5721,
    text: 'There shall be no restriction on the maximum permissible building height for group housing schemes. The height of the building in group housing project shall be governed by its distance from the protected monument/heritage site, airport funnel zone and other statutory restrictions if any.',
  },
  {
    id: 'setback.bazaar-street.note',
    rule: 'setback.bazaar-street',
    clause: 'Clause 3.2.4.3 Note-3',
    supports: 'The gazette prints this ladder twice, in Chapter 3 and Chapter 5, and the two copies are identical.',
    gazettePage: 58,
    kind: 'prose',
    line: 4554,
    text: 'Note-3: The permissible front setbacks for buildings on bazaar street shall be as follows (also defined in Chapter-5).',
  },
  {
    id: 'setback.bazaar-street.table',
    rule: 'setback.bazaar-street',
    clause: 'Clause 5.1.5 / 3.2.4.3 Note-3',
    supports: 'BAZAAR_STREET_FRONT_LADDER — the one setback table keyed on road width rather than plot area.',
    gazettePage: 85,
    kind: 'cells',
    lines: [4556, 4578],
    cells: [
      'Proposed width of road (metres)',
      'Minimum open space in front (metres)',
      '12',
      '3.0',
      '18',
      '4.5',
      '24',
      '6.0',
      '30',
      '6.0',
      '36',
      '7.5',
      '45',
      '7.5',
      '76',
      '9.0',
    ],
  },
  {
    id: 'occupancy.commercial.height',
    rule: 'occupancy.thresholds',
    clause: 'Clause 5.2.4',
    supports: 'com_shop / com_complex / com_mall maxHeightM = Infinity. com_shop previously carried 15 m.',
    gazettePage: 86,
    kind: 'prose',
    line: 6356,
    text: 'There shall be no restriction on building height for commercial buildings i.e. shops, commercial complex, shopping malls. However, the maximum height of the building shall be governed by distance from the protected monument/ heritage site, airport funnel zone and other statutory restrictions.',
  },
  {
    id: 'occupancy.bazaar.height',
    rule: 'occupancy.thresholds',
    clause: 'Clause 5.1.3(i)',
    supports: 'com_bazaar maxHeightM = Infinity. It previously carried 15 m.',
    gazettePage: 84,
    kind: 'prose',
    line: 6129,
    text: 'There shall be no restriction on building height for bazaar streets. However, the maximum height of the building shall be governed by distance from the protected monument/ heritage site, airport funnel zone and other statutory restrictions.',
  },
  {
    id: 'occupancy.hotel.thresholds',
    rule: 'occupancy.thresholds',
    clause: 'Clause 5.3.2 and 5.3.3',
    supports: 'Hotel thresholds turn on ROOM COUNT, which the engine does not model — see V-011.',
    gazettePage: 87,
    kind: 'prose',
    line: 6528,
    text: 'The minimum number of rooms in hotel building shall be six (6). Up to 20 rooms there shall be no restriction on the minimum plot area for construction of hotels. For construction of hotels with more than 20 rooms, the minimum plot area shall be 500 sqm.',
  },
  {
    id: 'far.purchasable.legend',
    rule: 'far.purchasable-commercial',
    clause: 'Clause 5.2.5 Note-1',
    supports: 'The meaning of BFAR, PFAR, PPFAR, MFAR and UR, stated by the gazette itself.',
    gazettePage: 86,
    kind: 'prose',
    line: 6511,
    text: 'Note-1: BFAR – Base FAR, PFAR – Purchasable FAR, PPFAR – Premium Purchasable FAR, MFAR – Maximum Permissible FAR which includes Base FAR, UR – Unrestricted FAR.',
  },
  {
    id: 'far.purchasable.commercial-table',
    rule: 'far.purchasable-commercial',
    clause: 'Clause 5.2.5',
    supports: 'COMMERCIAL_FAR_BREAKDOWN — six rows, four road bands each, MFAR = BFAR + PFAR + PPFAR on all 24 band checks.',
    gazettePage: 86,
    kind: 'cells',
    lines: [6389, 6510],
    cells: [
      'Built-up Area',
      'Comm. Units up to100 sqm',
      '1.5',
      '0.3',
      '0.3',
      '2.1',
      '0.75',
      '0.75',
      '3.0',
      '1.5',
      '2.25',
      '5.25',
      '1.5',
      'UR',
      'UR',
      'Comm. Units >100 sqm',
      '1.5',
      'NA',
      'NA',
      '1.5',
      '0.75',
      '0.75',
      '3.0',
      '1.5',
      '2.25',
      '5.25',
      '1.5',
      'UR',
      'UR',
      'Shopping malls',
      '2.0',
      'NA',
      'NA',
      '2.0',
      '1.0',
      '1.0',
      '4.0',
      '2.0',
      '3.0',
      '7.0',
      '2.0',
      'UR',
      'UR',
      'Non-Built-up Area',
      'Commercial Units* up to100 sqm',
      '1.75',
      '0.35',
      '0.35',
      '2.45',
      '0.9',
      '0.9',
      '3.6',
      '1.75',
      '2.6',
      '6.1',
      '1.75',
      'UR',
      'UR',
      'Commercial Units* >100 sqm',
      '1.75',
      'NA',
      'NA',
      '1.75',
      '0.9',
      '0.9',
      '3.6',
      '1.75',
      '2.6',
      '6.1',
      '1.75',
      'UR',
      'UR',
      'Shopping malls',
      '3.0',
      'NA',
      'NA',
      '3.0',
      '1.5',
      '1.5',
      '6',
      '3.0',
      '4.5',
      '10.5',
      '3.0',
      'UR',
      'UR',
      '*Commercial Units include Shops / Convenience Shopping / other commercial complexes etc.',
    ],
  },
  {
    id: 'far.purchasable.group-housing',
    rule: 'far.purchasable-commercial',
    clause: 'Clause 4.2.8',
    supports: 'Group housing, both area types. Built-up gives 2.1 on the narrowest band where Chapter 3 gives 2.0, and non-built-up gives an up-to-12 m band at 3.5 where Chapter 3 prints no band below 12 m.',
    gazettePage: 78,
    kind: 'cells',
    lines: [5776, 5865],
    cells: [
      'Built-up Area',
      'Group Housing',
      '1.5',
      '0.3',
      '0.3',
      '2.1',
      '0.75',
      '0.75',
      '3',
      '1.5',
      '2.25',
      '5.25',
      '1.5',
      'UR',
      'UR',
      'Non-Built-up Area',
      'Group Housing',
      '2.5',
      '0.5',
      '0.5',
      '3.5',
      '1.25',
      '1.25',
      '5',
      '2.5',
      '3.75',
      '8.75',
      '2.5',
      'UR',
      'UR',
    ],
  },
  {
    id: 'far.purchasable.affordable-housing',
    rule: 'far.purchasable-commercial',
    clause: 'Clause 4.4',
    supports: 'Affordable housing. Bands on 18 m rather than 12 m, and prints TWO base FARs for one use — 2.00 below 18 m and 2.25 at or above it — against one shared set of band columns.',
    gazettePage: 82,
    kind: 'cells',
    lines: [6025, 6088],
    cells: [
      'Group Housing',
      '(Built-up Area)',
      '2.00 (<18m)',
      '0.20',
      '0.20',
      '2.40',
      '1.00',
      '1.00',
      '2.00',
      '2.00',
      '3.00',
      '7.00',
      '2.00',
      'UR',
      'UR',
      'Group Housing',
      '(Built-up Area)',
      '2.25 (≥18m)',
      '0.23',
      '0.23',
      '2.71',
      '1.125',
      '1.125',
      '4.50',
      '2.25',
      '3.38',
      '7.88',
      '2.25',
      'UR',
      'UR',
      'Group Housing',
      '(Non-Built-up Area)',
      '3.00',
      '0.30',
      '0.30',
      '3.60',
      '1.50',
      '1.50',
      '6.00',
      '3.00',
      'UR',
      'UR',
      '3.00',
      'UR',
      'UR',
    ],
  },
  {
    id: 'far.purchasable.bazaar-street',
    rule: 'far.purchasable-commercial',
    clause: 'Clause 5.1.4',
    supports: 'Bazaar street, both area types. Nothing purchasable on the narrowest band.',
    gazettePage: 84,
    kind: 'cells',
    lines: [6173, 6263],
    cells: [
      'Built-up Area',
      'Bazaar Street',
      '1.5',
      'NA',
      'NA',
      '1.5',
      '0.75',
      '0.75',
      '3.0',
      '1.5',
      '2.25',
      '5.25',
      '1.5',
      'UR',
      'UR',
      'Non-Built-up Area',
      'Bazaar Street',
      '1.75',
      'NA',
      'NA',
      '1.75',
      '0.9',
      '0.9',
      '3.6',
      '1.75',
      '2.6',
      '6.1',
      '1.75',
      'UR',
      'UR',
    ],
  },
  {
    id: 'far.purchasable.hotels-built-up',
    rule: 'far.purchasable-commercial',
    clause: 'Clause 5.3.5',
    supports: 'Hotels in a built-up area. Chapter 3 prints no band below 12 m; Clause 5.3.3 allows a hotel of up to 20 rooms on a 9 m road, so this band is reachable.',
    gazettePage: 87,
    kind: 'cells',
    lines: [6580, 6609],
    cells: [
      'Built-up Area',
      'Hotels',
      '2.0',
      'NA',
      'NA',
      '2.0',
      '1.0',
      '1.0',
      '4.0',
      '2.0',
      '3.0',
      '7.0',
      '2.0',
      'UR',
      'UR',
    ],
  },
  {
    id: 'far.purchasable.hotels-new-layout',
    rule: 'far.purchasable-commercial',
    clause: 'Clause 5.3.5',
    supports: 'Hotels in a new layout.',
    gazettePage: 88,
    kind: 'cells',
    lines: [6651, 6681],
    cells: [
      'Non-Built-up Area',
      'Hotels',
      '2.5',
      'NA',
      'NA',
      '2.5',
      '1.25',
      '1.25',
      '5.0',
      '2.5',
      '3.75',
      '8.75',
      '2.5',
      'UR',
      'UR',
    ],
  },
  {
    id: 'far.purchasable.cinema',
    rule: 'far.purchasable-commercial',
    clause: 'Clause 5.4.4',
    supports: 'Single-screen cinema, miniplex and multiplex. The narrowest band prints no maximum at all — not permitted below a 12 m road — and non-built-up multiplex gives 10.5 above 24 m where Chapter 3 gives 9.0.',
    gazettePage: 90,
    kind: 'cells',
    lines: [6774, 6849],
    cells: [
      'Built-up Area',
      'Cinema, Miniplex, Multiplex',
      '2.0',
      'NA',
      'NA',
      'NA',
      '1.0',
      '1.0',
      '4.0',
      '2.0',
      '3.0',
      '7.0',
      '2.0',
      'UR',
      'UR',
      'Non-Built-up Area',
      'Cinema, Miniplex',
      '2.0',
      'NA',
      'NA',
      'NA',
      '1.0',
      '1.0',
      '4.0',
      '2.0',
      '3.0',
      '7.0',
      '2.0',
      'UR',
      'UR',
      'Multiplex',
      '3.0',
      'NA',
      'NA',
      'NA',
      '1.5',
      '1.5',
      '6.0',
      '3.0',
      '4.5',
      '10.5',
      '3.0',
      'UR',
      'UR',
    ],
  },
  {
    id: 'occupancy.healthcare.plot',
    rule: 'occupancy.thresholds',
    clause: 'Clause 6.1.2',
    supports: 'Five healthcare facilities from 100 m² to 3000 m². inst_health holds 500 m², which matches none of them.',
    gazettePage: 94,
    kind: 'cells',
    lines: [6960, 6987],
    cells: [
      'Healthcare facility',
      'Min. Plot area (sqm)',
      '1',
      'Non-Bedded Medical Establishments (Diagnostic Centre/ OPD clinics/ dispensary/ Pathology Lab/ Veterinary Clinics)',
      '100',
      '2',
      'Nursing Homes / Veterinary Hospitals / Maternity Hospitals/ Small Hospitals (Up to 50 beds)',
      '300',
      '3',
      'Hospitals (> 50 beds)',
      '3000',
      '4',
      'Nursing Institutes',
      '2000',
      '5',
      'Medical College',
      'As per NMC / MCI norms',
      'Means of Access',
      'The minimum width of the existing approach road shall be as follows:',
      'Sl.',
    ],
  },
  {
    id: 'occupancy.healthcare.road',
    rule: 'occupancy.thresholds',
    clause: 'Clause 6.1.3',
    supports: 'Road minimums 9 / 12 / 18 / 18 / 24 m for the same five facilities. inst_health holds 12 m.',
    gazettePage: 94,
    kind: 'cells',
    lines: [6988, 7006],
    cells: [
      'Healthcare facility',
      'Min. Road Width (m)',
      '1',
      'Non-Bedded Medical Establishments (Diagnostic Centre/ OPD clinics/ dispensary/ Pathology Lab/ Veterinary Clinics)',
      '9',
      '2',
      'Nursing Homes / Veterinary Hospitals / Maternity Hospitals/ Small Hospitals (Up to 50 beds)',
      '12',
      '3',
      'Hospitals (> 50 beds)',
      '18',
      '4',
      'Nursing Institutes',
      '18',
    ],
  },
  {
    id: 'occupancy.education.plot',
    rule: 'occupancy.thresholds',
    clause: 'Clause 6.2.2',
    supports: 'Five education facilities from 500 m² to 20000 m². inst_education holds 1000 m².',
    gazettePage: 96,
    kind: 'cells',
    lines: [7249, 7277],
    cells: [
      'Educational facility',
      'Min. Plot area (sqm)',
      '1',
      'Nursery',
      '500',
      '2',
      'Primary',
      '1000',
      '3',
      'Secondary / High School / Intercollege',
      '2000',
      '4',
      'Degree College / Technical Institution',
      '5000',
      '5',
      'Universities',
      '20000',
      'However, in case of spatial norms (for minimum plot areas and land requirements based on student intake and specializations covered, minimum standards for play areas, playground and open spaces) for construction of schools, colleges and universities prescribed by Central Public Works Department (CPWD) or affiliated institutions like Uttar Pradesh State Education Board (UPSEB)/ Central Board for School Education (CBSE), Indian Certificate for Secondary Education (ICSE), All India Council for Technical Education (AICTE), University Grants Commission (UGC), etc., differ from the above norms as defined by regulatory/affiliated agencies shall prevail. For example, minimum playground area (for Class 1-8 / 10 / 12) of 1000 sqm as prescribed by CBSE norms (amended time to time) shall prevail.',
      'Means of Access',
      'The minimum width of the access road shall be as follows:',
      'Sl.',
    ],
  },
  {
    id: 'occupancy.education.road',
    rule: 'occupancy.thresholds',
    clause: 'Clause 6.2.3',
    supports: 'Road minimums 9 / 9-or-12 / 12 / 18 / 24 m. Primary school splits by area type.',
    gazettePage: 96,
    kind: 'cells',
    lines: [7278, 7296],
    cells: [
      'Educational building',
      'Min. Road Width (m)',
      '1',
      'Nursery',
      '9',
      '2',
      'Primary School',
      '9 – Built-up area',
      '12 – Non-Built-up area',
      '3',
      'Secondary/ High School',
      '12',
      '4',
      'Degree College/ Technical Institution',
      '18',
    ],
  },
  {
    id: 'occupancy.assembly.plot',
    rule: 'occupancy.thresholds',
    clause: 'Clause 6.3.2',
    supports: 'inst_assembly.minPlotAreaSqm — 750 m² built-up, 1000 m² in a new layout.',
    gazettePage: 98,
    kind: 'prose',
    line: 7510,
    text: 'Minimum plot size for the construction of marriage hall, banquet or a multi-purpose hall shall be 750 square meters for built-up area and 1000 square meters for non-built-up area.',
  },
  {
    id: 'occupancy.industry.plot',
    rule: 'occupancy.thresholds',
    clause: 'Clause 7.1.2',
    supports: 'ind_light and ind_general minPlotAreaSqm = 0. The engine imposed 200 m² and 1000 m².',
    gazettePage: 101,
    kind: 'prose',
    line: 7774,
    text: 'There is no restriction on the minimum plot size for industrial buildings, flatted factories, data centres and MSME units as per paragraph 3.2.1 of the building byelaws.',
  },
  {
    id: 'occupancy.farmhouse',
    rule: 'occupancy.thresholds',
    clause: 'Clause 7.2.2',
    supports: 'Farmhouse: 4000 m² minimum plot. Not modelled as an occupancy — see V-022.',
    gazettePage: 102,
    kind: 'prose',
    line: 7960,
    text: 'The minimum plot area for the construction of farmhouse shall be 4000 sq.m.',
  },
  {
    id: 'occupancy.dairy',
    rule: 'occupancy.thresholds',
    clause: 'Clause 7.3.2',
    supports: 'Dairy farm / gaushala: 1000 m² minimum plot. Not modelled as an occupancy — see V-022.',
    gazettePage: 103,
    kind: 'prose',
    line: 7978,
    text: 'The minimum plot size for dairy farm/ gaushala shall be 1000 square meters.',
  },
  {
    id: 'occupancy.industry.road',
    rule: 'occupancy.thresholds',
    clause: 'Clause 7.1.3',
    supports: 'Road minimum split by USE ZONE — 7 m agriculture, 9 m industrial, 12 m for flatted factories and data centres. A third dimension after facility and area type; see V-021.',
    gazettePage: 101,
    kind: 'cells',
    lines: [7778, 7793],
    cells: [
      'Industries',
      'Minimum Road Width (m)',
      '1',
      'Industrial Buildings',
      '7-meters (Agriculture Use Zone) 9-meters (Industrial Use Zones)',
      '2',
      'Flatted Factories',
      '12-meters (Industrial Use Zone)',
      '3',
      'Data Centers',
      '12',
      '4',
    ],
  },
  {
    id: 'far.mixed-use.scope',
    rule: 'far.mixed-use',
    clause: 'Clause 8.1.3.1',
    supports: 'Which locations the mixed-use FAR table governs — 8.1.2(a) and (b). The standards table sends both of them to "para 8.1.3.6", which does not exist; this line is what identifies 8.1.3.1 as the table it meant.',
    gazettePage: 105,
    kind: 'prose',
    line: 8106,
    text: 'Mixed-use buildings described in paragraph 8.1.2 (a) and (b) shall avail FAR as per table below:',
  },
  {
    id: 'far.mixed-use.table',
    rule: 'far.mixed-use',
    clause: 'Clause 8.1.3.1 Table',
    supports: 'MIXED_USE_MAX_FAR and BASE_FAR.mixed_use — base 2.0 built-up and 2.5 in a new layout, against four road bands. Two cells contradict themselves and resolve to 4.5 and 6.25; see GAZETTE_ARITHMETIC_DEFECTS.',
    gazettePage: 105,
    kind: 'cells',
    lines: [8108, 8163],
    cells: [
      'FAR',
      '3047-239238Mixed Use Buildings',
      'BFAR',
      'Road Width (Upto12m)',
      'Road Width (12 -24m)',
      'Road Width (24 - 45m)',
      'Road Width (>45m)',
      'PFAR',
      'PPFAR',
      'MFAR',
      'PFAR',
      'PPFAR',
      'MFAR',
      'PFAR',
      'PPFAR',
      'MFAR',
      'PFAR',
      'PPFAR',
      'MFAR',
      'MU Built-up Area',
      '2.0',
      'NA',
      'NA',
      '2.0',
      '1.0',
      '1.0',
      '4.0',
      '1.0',
      '1.5',
      '5.25',
      '1.5',
      'UR',
      'UR',
      'MU non-built-up Area',
      '2.5',
      'NA',
      'NA',
      '2.5',
      '1.25',
      '1.25',
      '5.0',
      '2.5',
      '3.75',
      '6.25',
      '2.5',
      'UR',
      'UR',
    ],
  },
  {
    id: 'occupancy.mixed-use.standards',
    rule: 'occupancy.thresholds',
    clause: 'Clause 8.1.3 Table',
    supports: 'Mixed use: no minimum plot size and no height restriction in any of the five locations, parking per the higher use, and a means of access that runs 9 m to 24 m across them. The engine held 300 m² and 1.75 ECS/100 m², neither of which appears here. See V-024.',
    gazettePage: 104,
    kind: 'cells',
    lines: [8025, 8098],
    cells: [
      'Parameter/Development Standard',
      'Mixed use zones earmarked under Master Plan',
      'Mixed use plots as part of approved layouts',
      'Notified bazaar streets',
      'Along 24-meter and wider roads',
      'TOD zones',
      'Minimum Plot Size',
      'No restriction',
      'No restriction',
      'No restriction',
      'No restriction',
      'No restriction',
      'Means of Access',
      '9m (plots upto 100 sqm); 12m (other plots)',
      '24m',
      '12m',
      '24m',
      '=>12m',
      'Building Height',
      'Not restricted',
      'Not restricted',
      'Not restricted',
      'Not restricted',
      'Not restricted',
      'Minimum Setbacks',
      'As applicable for higher use',
      'As applicable for higher use',
      'As per para 5.1.5',
      'As applicable for higher use',
      'As applicable for higher use',
      'Floor Area Ratio',
      'As per para 8.1.3.6',
      'As per para 8.1.3.6',
      'As per para 5.1.4',
      'As per Use Zone',
      'As per para 8.2.2.2',
      'Mixing',
      '0-100%',
      '0-100%',
      'Commercial (2 floors)',
      '=>33% (principal',
      'use); =<67% (other uses)',
      '=>33% (principal',
      'use); =<67% (other uses)',
      'However, share of single other use shall not be more than principal use.',
      'However, share of single other use shall not be more than principal use.',
      'Parking',
      'As per proposed higher use',
      'As per proposed higher use',
      'As per proposed higher use',
      'As per 3.3.4',
      '1ECS per 100 sqm.',
      'Ground Coverage',
      'Subject to adherence to prescribed setbacks',
      'Subject to adherence to prescribed setbacks',
      'Subject to adherence to prescribed setbacks',
      'Subject to adherence to prescribed setbacks',
      'Subject to adherence to prescribed setbacks',
    ],
  },
  {
    id: 'far.tod.table',
    rule: 'far.tod',
    clause: 'Clause 8.2.2.2 Table',
    supports: 'TOD_FAR_BANDS — TOD FAR as a percentage of base FAR: 150 / 250 / 350 / unrestricted, the only FAR rule in the byelaws stated as a multiplier.',
    gazettePage: 106,
    kind: 'cells',
    lines: [8215, 8233],
    cells: [
      'Minimum Right of Way',
      'Base FAR',
      'TOD FAR as % of Base FAR',
      '12m',
      'As per byelaws',
      '150%',
      '>12 - 24m',
      'As per byelaws',
      '250%',
      '>24 - 45m',
      'As per byelaws',
      '350%',
      '>45m',
      'As per byelaws',
      'Unrestricted',
    ],
  },
  {
    id: 'far.tod.premium-charge',
    rule: 'far.tod',
    clause: 'Clause 8.2.2.2 Note (2)',
    supports: 'TOD_PREMIUM_CHARGED_AS_PURCHASABLE — in a TOD zone premium purchasable FAR is charged at the purchasable rate, the one place the two prices collapse together.',
    gazettePage: 106,
    kind: 'prose',
    line: 8237,
    text: 'For availing maximum permissible FAR, charges of purchasable FAR only shall apply. That is to say, that the charges for purchasable FAR and premium purchasable FAR shall be the same.',
  },
  {
    id: 'far.tod.predominance',
    rule: 'far.tod',
    clause: 'Clause 8.2.2.1 Note',
    supports: 'The predominance bar behind MIXING_RULE: the master-plan land use must remain predominant, which is why checkMixing takes the principal use as given rather than reading it off the largest share.',
    gazettePage: 106,
    kind: 'prose',
    line: 8211,
    text: 'Note* - Subject to restriction that MP/ZDP/layout land use shall remain pre-dominant land use.',
  },
  {
    id: 'far.purchase-gate.road-width',
    rule: 'far.purchase-gate',
    clause: 'Clause 9.2.1(ii)',
    supports:
      'PURCHASABLE_FAR_MIN_ROAD_WIDTH = 12, and the 9 m exception canPurchaseFarAt() makes for group housing in a built-up area.',
    gazettePage: 109,
    kind: 'prose',
    line: 8289,
    text: 'Purchasable and premium purchasable FAR shall be allowed only on roads with ROW 12m and above in built-up and non-built-up areas. For group housing in built-up areas, this is allowed on roads with ROW 9m.',
  },
  {
    id: 'far.purchase-gate.plotted-exception',
    rule: 'far.purchase-gate',
    clause: 'Clause 9.2.3 Note 1',
    supports:
      'The second exception in canPurchaseFarAt(): plotted residential is exempt from the road-width bar entirely, so a 4 m lane does not stop the purchase.',
    gazettePage: 110,
    kind: 'prose',
    line: 8366,
    text: 'Note 1: In case of residential plotted development, calculation of purchasable FAR is not dependent on the width of the approach road and will be allowed on minimum 9-m /7.5-m or 4.0-m road as the case may be.',
  },
  {
    id: 'far.purchasable-commercial.master-table',
    rule: 'far.purchasable-commercial',
    clause: 'Clause 9.2.3 Table',
    supports:
      'The master purchasable ladder, recorded for the defect in its own MFAR column: PFAR and PPFAR are stated as percentages of B2, B3 and B4, but every MFAR cell says "of B1". Rows 2 and 3 do not add up as printed — see V-029. The engine reads the per-chapter tables, which Note-2 makes prevail.',
    gazettePage: 109,
    kind: 'cells',
    lines: [8301, 8336],
    cells: [
      'Road Width (m)',
      'Base FAR (BFAR)',
      'Purchasable FAR (PFAR)',
      'Premium Purchasable FAR (PPFAR)',
      'Maximum Permissible FAR (MFAR)',
      '(1)',
      '(2)',
      '(3)',
      '(4)',
      '(5) = (2)+(3)+(4)',
      'Up to 12m',
      'B1',
      'Up to 20% of B1',
      'Up to 20% of B1',
      '140% of B1',
      '12 – 24m',
      'B2',
      'Up to 50% of B2',
      'Up to 50% of B2',
      '200% of B1',
      '24 – 45m',
      'B3',
      'Up to 100% of B3',
      'Up to 150% of B3',
      '350% of B1',
      'More than 45m',
      'B4',
      'Up to 100% of B4',
      'Unrestricted*',
      'Unrestricted*',
    ],
  },
  {
    id: 'far.purchasable-commercial.chapter-precedence',
    rule: 'far.purchasable-commercial',
    clause: 'Clause 9.2.3 Note-2',
    supports:
      'Why purchasable-far.json carries the per-occupancy tables from chapters 3 to 7 rather than this chapter’s master ladder: where they differ, the chapters win.',
    gazettePage: 109,
    kind: 'prose',
    line: 8338,
    text: 'Note-2: In case of any difference in the prescribed limits of maximum permissible FAR in chapter-3 to chapter-7 and the table above, the figures in respective chapters will prevail.',
  },
  {
    id: 'far.purchasable-fee.formula',
    rule: 'far.purchasable-fee',
    clause: 'Clause 9.2.5',
    supports:
      'assessPurchaseFee() — C = Le × Rc × P, with Le = FP ÷ Base FAR and FP = the additional floor area availed.',
    gazettePage: 110,
    kind: 'prose',
    line: 8380,
    text: 'Purchasable and Premium Purchasable FAR fee shall be calculated as per the following formula: - C = Le x Rc x P',
  },
  {
    id: 'far.purchasable-fee.land-rate',
    rule: 'far.purchasable-fee',
    clause: 'Clause 9.2.5 Note (Rc)',
    supports:
      'What Rc means: the higher of the District Magistrate’s circle rate and the Authority’s residential rate, which is why PurchaseInput takes one resolved landRate rather than a rate type.',
    gazettePage: 111,
    kind: 'prose',
    line: 8387,
    text: 'Note: The current rate of land refers to the circle rate determined by the District Magistrate, where such rate is not available, the current residential rate determined by the Authority/Awas Vikas Parishad whichever is higher.',
  },
  {
    id: 'far.purchasable-fee.factor-coefficients',
    rule: 'far.purchasable-fee',
    clause: 'Clause 9.2.5 Table',
    supports:
      'FACTOR_COEFFICIENTS — the seven land-use categories of purchasableFarCategory and their P values. Residential (Plotted) prints a dash in the premium column, which the engine holds as null rather than 0.',
    gazettePage: 111,
    kind: 'cells',
    lines: [8391, 8430],
    cells: [
      'Sl.',
      'Land Use Category',
      'Factor Coefficient (P) Purchasable FAR',
      'Factor Coefficient (P) Premium Purchasable FAR',
      '1',
      'Commercial',
      '0.50',
      '1.0',
      '2',
      'Mixed Use',
      '0.45',
      '0.9',
      '3',
      'Office Buildings / Institutional',
      '0.45',
      '0.9',
      '4',
      'Hotels',
      '0.40',
      '0.8',
      '5',
      'Residential (Plotted)',
      '0.40',
      '-',
      '6',
      'Residential (Group Housing)',
      '0.40',
      '0.8',
      '7',
      'Community Facilities and Infrastructure',
      '0.20',
      '0.4',
    ],
  },
  {
    id: 'far.green-incentive.silver',
    rule: 'far.green-incentive',
    clause: 'Clause 9.3(a)',
    supports:
      'GREEN_FAR_BONUS.silver = 0.03.',
    gazettePage: 111,
    kind: 'prose',
    line: 8514,
    text: 'GRIHA Three star/ IGBC Silver / LEED silver or equivalent rating – 3% additional FAR on availed FAR.',
  },
  {
    id: 'far.green-incentive.gold',
    rule: 'far.green-incentive',
    clause: 'Clause 9.3(b)',
    supports:
      'GREEN_FAR_BONUS.gold = 0.05.',
    gazettePage: 111,
    kind: 'prose',
    line: 8515,
    text: 'GRIHA Four star/IGBC Gold/LEED Gold or equivalent rating – 5% additional FAR on availed FAR.',
  },
  {
    id: 'far.green-incentive.platinum',
    rule: 'far.green-incentive',
    clause: 'Clause 9.3(c)',
    supports:
      'GREEN_FAR_BONUS.platinum = 0.07.',
    gazettePage: 112,
    kind: 'prose',
    line: 8517,
    text: 'GRIHA Five star/ IGBC Platinum/ LEED Platinum or equivalent rating – 7% additional FAR on availed FAR.',
  },
  {
    id: 'far.green-incentive.above-mfar',
    rule: 'far.green-incentive',
    clause: 'Clause 9.3 Note I',
    supports:
      'Why resolveBaseFar adds the green bonus on top of the ceiling instead of inside it, and why the bonus needs a pre-certification to be claimed at all.',
    gazettePage: 112,
    kind: 'prose',
    line: 8519,
    text: 'Additional FAR mentioned above in point a), b) and c) shall be awarded after pre-certification from the empanelled agency. This incentive FAR on Green Buildings shall be over and above the MFAR.',
  },
  {
    id: 'far.green-incentive.penalty',
    rule: 'far.green-incentive',
    clause: 'Clause 9.3 Note II',
    supports:
      'GREEN_RATING_SHORTFALL_PENALTY_MULTIPLE = 2 and greenRatingShortfallPenalty() — the incentive is reversible at twice the circle-rate land cost.',
    gazettePage: 112,
    kind: 'prose',
    line: 8520,
    text: 'In case that the developer fails to achieve committed rating as per pre-certification at the time of final occupancy, a penalty shall be imposed at the rate 2 times of the land cost as per the circle rates for the additional FAR for the rating not achieved.',
  },
];

/** Every rule id that has at least one citation. */
export const CITED_RULES: ReadonlySet<string> = new Set(CITATIONS.map((c) => c.rule));
