#!/usr/bin/env bash
# Regenerate every derived extraction from the checked-in originals, and record which
# bytes each one came from. Safe to re-run: the output is a pure function of the inputs.
set -euo pipefail
cd "$(dirname "$0")/.."

python3 tools/extract-chapter.py --all

if [ -f docs/source/gazette/pdf/chapter-03.pdf ]; then
  python3 tools/extract-far-matrix.py > docs/source/derived/far-matrix.json
fi

python3 tools/extract-purchasable-far.py > docs/source/derived/purchasable-far.json
python3 tools/extract-thresholds.py > docs/source/derived/thresholds.json

if [ -f docs/source/gazette/pdf/chapter-08.pdf ]; then
  python3 tools/extract-mixed-use.py > docs/source/derived/mixed-use.json
fi

if [ -f docs/source/gazette/pdf/chapter-15.pdf ]; then
  python3 tools/extract-zoning-matrix.py docs/source/gazette/pdf/chapter-15.pdf \
    > docs/source/derived/zoning-matrix.json
fi

{
  echo "# Generated by tools/extract-all.sh — do not edit."
  echo "# md5 of every original. Derived files under docs/source/derived/ are"
  echo "# reproducible from exactly these bytes."
  echo
  ( cd docs/source/gazette && md5sum UP-Building-Byelaws-2025-TMPR8.docx pdf/*.pdf )
} > docs/source/gazette/CHECKSUMS.txt

echo "done — $(ls docs/source/gazette/pdf/*.pdf | wc -l) chapter PDFs extracted"
