import raw from './gazette-documents.json';
import { BYELAW_CHAPTERS } from './byelawsData';

/**
 * The gazette documents the reader can open, measured from the files themselves.
 *
 * Generated by tools/build-gazette-manifest.py from docs/source/gazette/pdf/ — the same
 * originals every rule cites and CHECKSUMS.txt covers. Page counts and sizes here are
 * read off the bytes, not asserted, so the index can never describe a document the
 * reader does not get.
 */
export interface GazetteDocument {
  id: string;
  kind: 'chapter' | 'appendix';
  number: number;
  /** Served from the site root; see the gazettePdfs() plugin in vite.config.ts. */
  file: string;
  pdfPages: number;
  gazetteFrom: number | null;
  gazetteTo: number | null;
  bytes: number;
  md5: string;
  title: string;
  summary: string;
}

const APPENDIX_TITLES: Record<number, { title: string; summary: string }> = {
  15: {
    title: 'Use zones of the master plans',
    summary:
      'The land use zones each of the 22 Development Authorities actually prints on its '
      + 'master plan, mapped to the 16 standard zones of Clause 15.2.',
  },
};

export const GAZETTE_DOCUMENTS: readonly GazetteDocument[] = (raw.documents as Array<
  Omit<GazetteDocument, 'title' | 'summary'> & { kind: string }
>).map((doc) => {
  const chapter = doc.kind === 'chapter'
    ? BYELAW_CHAPTERS.find((c) => c.id === doc.number)
    : undefined;
  const appendix = doc.kind === 'appendix' ? APPENDIX_TITLES[doc.number] : undefined;
  return {
    ...doc,
    kind: doc.kind as GazetteDocument['kind'],
    title: chapter?.title ?? appendix?.title ?? `${doc.kind} ${doc.number}`,
    summary: chapter?.summary ?? appendix?.summary ?? '',
  };
});

export const GAZETTE_TOTAL_PAGES = GAZETTE_DOCUMENTS.reduce((n, d) => n + d.pdfPages, 0);
export const GAZETTE_TOTAL_BYTES = GAZETTE_DOCUMENTS.reduce((n, d) => n + d.bytes, 0);

export function documentLabel(doc: GazetteDocument): string {
  return doc.kind === 'chapter' ? `Chapter ${doc.number}` : `Appendix-${doc.number}`;
}

/** "pp. 113–115", or the page count alone where the gazette numbering is unknown. */
export function gazetteRange(doc: GazetteDocument): string {
  if (doc.gazetteFrom === null || doc.gazetteTo === null) {
    return `${doc.pdfPages} page${doc.pdfPages === 1 ? '' : 's'}`;
  }
  return doc.gazetteFrom === doc.gazetteTo
    ? `p. ${doc.gazetteFrom}`
    : `pp. ${doc.gazetteFrom}–${doc.gazetteTo}`;
}

export function formatBytes(bytes: number): string {
  return bytes >= 1_048_576
    ? `${(bytes / 1_048_576).toFixed(1)} MB`
    : `${Math.round(bytes / 1024)} KB`;
}
